"""Anonymized historical operation-time priors for costing support.

These values are intentionally non-confidential and should be treated as
historical seed priors, not immutable truth.
"""

from __future__ import annotations

OPERATION_TIME_BASELINES = [
    {
        "operationType": "laser_sheet_cutting",
        "workCenter": "LASER",
        "sampleCount": 245,
        "medianSeconds": 24.0,
        "averageSeconds": 63.2,
        "minSeconds": 4.0,
        "maxSeconds": 1000.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "laser_tube_or_profile_cutting",
        "workCenter": "LASER DO RUR",
        "sampleCount": 158,
        "medianSeconds": 25.5,
        "averageSeconds": 41.8,
        "minSeconds": 4.0,
        "maxSeconds": 240.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "cnc_bending_sheet",
        "workCenter": "GIĘTARKA SAFAN",
        "sampleCount": 101,
        "medianSeconds": 60.0,
        "averageSeconds": 67.8,
        "minSeconds": 15.0,
        "maxSeconds": 450.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "cnc_bending_sheet",
        "workCenter": "GIĘTARKI CNC",
        "sampleCount": 4,
        "medianSeconds": 255.0,
        "averageSeconds": 255.0,
        "minSeconds": 60.0,
        "maxSeconds": 450.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "cnc_bending_tube",
        "workCenter": "GIĘTARKI CNC",
        "sampleCount": 22,
        "medianSeconds": 30.0,
        "averageSeconds": 42.9,
        "minSeconds": 15.0,
        "maxSeconds": 160.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "cnc_bending_wire",
        "workCenter": "GIĘTARKI CNC",
        "sampleCount": 90,
        "medianSeconds": 12.0,
        "averageSeconds": 25.9,
        "minSeconds": 3.0,
        "maxSeconds": 473.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "wire_straightening_cutting",
        "workCenter": "PROŚCIARKI",
        "sampleCount": 112,
        "medianSeconds": 9.5,
        "averageSeconds": 21.0,
        "minSeconds": 1.0,
        "maxSeconds": 96.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "mig_manual_welding",
        "workCenter": "SPAWALNIA",
        "sampleCount": 115,
        "medianSeconds": 240.0,
        "averageSeconds": 500.5,
        "minSeconds": 30.0,
        "maxSeconds": 4500.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "robot_welding",
        "workCenter": "ROBOT",
        "sampleCount": 13,
        "medianSeconds": 980.0,
        "averageSeconds": 819.8,
        "minSeconds": 40.0,
        "maxSeconds": 1620.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "spot_welding",
        "workCenter": "ZGRZEWARKI",
        "sampleCount": 62,
        "medianSeconds": 72.0,
        "averageSeconds": 208.2,
        "minSeconds": 6.0,
        "maxSeconds": 1275.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "spot_welding",
        "workCenter": "ZGRZEWARKI AUTOMATYCZNE",
        "sampleCount": 22,
        "medianSeconds": 115.0,
        "averageSeconds": 136.0,
        "minSeconds": 8.0,
        "maxSeconds": 310.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "deburring_manual_finishing",
        "workCenter": "PRASY",
        "sampleCount": 40,
        "medianSeconds": 28.0,
        "averageSeconds": 38.4,
        "minSeconds": 6.0,
        "maxSeconds": 87.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "deburring_manual_finishing",
        "workCenter": "GRADOWARKA BĘBEN",
        "sampleCount": 5,
        "medianSeconds": 24.0,
        "averageSeconds": 24.0,
        "minSeconds": 24.0,
        "maxSeconds": 24.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "grinding",
        "workCenter": "PRASY",
        "sampleCount": 36,
        "medianSeconds": 60.0,
        "averageSeconds": 120.6,
        "minSeconds": 5.0,
        "maxSeconds": 1500.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "assembly",
        "workCenter": "MONTAŻ",
        "sampleCount": 28,
        "medianSeconds": 120.0,
        "averageSeconds": 294.6,
        "minSeconds": 60.0,
        "maxSeconds": 4200.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "packaging",
        "workCenter": "PAKOWANIE",
        "sampleCount": 231,
        "medianSeconds": 10.0,
        "averageSeconds": 13.9,
        "minSeconds": 1.0,
        "maxSeconds": 300.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "pressing",
        "workCenter": "PRASA AUTOMATYCZNA 100t",
        "sampleCount": 8,
        "medianSeconds": 1.0,
        "averageSeconds": 1.4,
        "minSeconds": 1.0,
        "maxSeconds": 2.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "pressing",
        "workCenter": "PRASY MIMOŚRODOWE",
        "sampleCount": 8,
        "medianSeconds": 5.5,
        "averageSeconds": 7.0,
        "minSeconds": 1.0,
        "maxSeconds": 24.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "saw_or_profile_cutting",
        "workCenter": "LASER DO RUR",
        "sampleCount": 35,
        "medianSeconds": 26.0,
        "averageSeconds": 79.7,
        "minSeconds": 4.0,
        "maxSeconds": 750.0,
        "source": "anonymized_historical_excel_baseline",
    },
    {
        "operationType": "milling",
        "workCenter": "NARZĘDZIOWNIA HAAS",
        "sampleCount": 4,
        "medianSeconds": 330.0,
        "averageSeconds": 285.0,
        "minSeconds": 120.0,
        "maxSeconds": 360.0,
        "source": "anonymized_historical_excel_baseline",
    },
]
